### ISSUE TITLE
 IIS of the application

### ISSUE THREAD

**Issue by aricordova** [miratechcorp/DirectoryListing#10]
hi, done installation in IIS of the application, when browsing folder, I get error, can you help?
![err2](https://user-images.githubusercontent.com/65923609/82846218-2631e380-9ebe-11ea-9745-8cf86e0dc2c4.PNG)

should be http:  //localhost/SGI/ ICONES

![err](https://user-images.githubusercontent.com/65923609/82846142-d521ef80-9ebd-11ea-8c4b-2ffb5511c2b9.PNG)

**Comment by schmalls** [comment]
I am thinking this is not an issue with the application but with how you have IIS setup.
