### ISSUE TITLE
Can't get DirectoryListing working

### ISSUE THREAD

**Issue by kotsch** [miratechcorp/DirectoryListing#7]
I have extracted the folder **directorylisting-master** to the **wwwroot** directory of the IIS8 Homepage.
Then i changed the root directory in the web.config file to the directory c:\inetpub\wwwroot\test.
Browsing the test page, there is no change. When I disable the directory browsing I get error 403.14.

Enable directory browsing again, shows me the original outlook.

My Folder are looking like this:

ThisPC > Local Disk C: > inetpub > wwwroot >

Folder: test
Folder: DirectoryListing-master
  iis-85.png
  iisstart.htm

Sorry, I'm new within IIS and don't know how to work with ASP.

Thanks for any help

**Comment by schmalls** [comment]
It sounds like you don't have the application setup correctly in IIS. This isn't really a support forum for learning how to use IIS. The [Microsoft docs](https://docs.microsoft.com/en-us/iis/get-started/getting-started-with-iis/getting-started-with-the-iis-manager-in-iis-7-and-iis-8) might be a good place to start.
